# Generated by Django 5.1 on 2024-08-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinmobiliaria', '0002_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.CharField(max_length=100),
        ),
    ]
