# Generated by Django 5.1 on 2024-08-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinmobiliaria', '0004_alter_propiedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
