# Generated by Django 5.1 on 2024-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinmobiliaria', '0005_alter_propiedad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.CharField(default=222, max_length=300),
            preserve_default=False,
        ),
    ]
