# Generated by Django 5.0.3 on 2024-08-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinmobiliaria', '0006_propiedad_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
